version: '3'

services:
  postgres:
      image: postgres:14beta3
      volumes:
        - ./pgdata:/var/lib/postgresql/data
        - ./backups:/backups
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  keycloak:
      image: jboss/keycloak:15.0.1
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
      volumes:
        - /Users/arpit.shah/Documents/Review/Others/caringly/keycloak/certs/tls.crt:/etc/x509/https/tls.crt
        - /Users/arpit.shah/Documents/Review/Others/caringly/keycloak/certs/tls.key:/etc/x509/https/tls.key
      ports:
        - 8080:8080
        - 8443:8443
      depends_on:
        - postgres
